import Header from "./header"; 
import Footer from "./Footer"; 
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased" style={{ fontFamily: '"Lucida Bright"' }}>
      <body 
        className="min-h-full flex flex-col"
        style={{ fontFamily: '"Lucida Bright", Georgia, serif' }}
      >
        {/* Top par Header */}
        <Header />

        {/* Dynamic Page Content */}
        <main className="flex-grow">{children}</main>

        {/* Bottom par Footer */}
        <Footer />
      </body>
    </html>
  );
}